Recruitment_Support_System/Models/JobOffer.cs
using Recruitment_Support_System.Models.CurriculumVitae;
using Recruitment_Support_System.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Recruitment_Support_System.Models
{
    public class JobOffer
    {
        private int id;
        private Company company;
        private string title;
        private string about;
        private string responsibilities;
        private string requirements;
        private Int16 teamSize;
        private long zarobkiMin;
        private long zarobkiMax;
        private string currency;
        private billingPeriod okresRozliczeniowy;
        private JobLevel jobLevel;
        private JobContract jobContract;
        private string[] skills;
        private bool remote;
        private bool remoteInterview;
        private bool isDeleted;
        private DateTime expirationDate;

        public int Id { get => id; set => id = value; }
        public Company Company { get => company; set => company = value; }
        [Display(Name = "Tytuł")]
        public string Title { get => title; set => title = value; }

        [Display(Name = "Opis")]
        public string About { get => about; set => about = value; }
        [Display(Name = "Obowiązki")]
        public string Responsibilities { get => responsibilities; set => responsibilities = value; } //TODO: split them with something like & or ~.
        [Display(Name = "Wymagania")]
        public string Requirements { get => requirements; set => requirements = value; } //TODO: same here
        [Display(Name = "Wielkość zespołu")]
        public short TeamSize { get => teamSize; set => teamSize = value; }
        [Display(Name = "Poziom stanowiska")]
        public JobLevel JobLevel { get => jobLevel; set => jobLevel = value; }
        [Display(Name = "Rodzaj umowy")]
        public JobContract JobContract { get => jobContract; set => jobContract = value; }
        public string[] Skills { get => skills; set => skills = value; }
        [Display(Name = "Wymagane umiejętności", Description = "Wpisz wymagane umiejętności odzielone spacją")]
        public string Skill
        {
            get => skills == null ? "" : string.Join(" ", skills);
            set => skills = value.Split(' ');
        }
        public ICollection<Application> Applications { get; set; }
        [Display(Name = "Minimalne zarobki")]
        public long ZarobkiMin { get => zarobkiMin; set => zarobkiMin = value; }
        [Display(Name = "Maxymalne zarobki")]
        public long ZarobkiMax { get => zarobkiMax; set => zarobkiMax = value; }
        [Display(Name = "Okres  rozliczeniowy")]
        public billingPeriod OkresRozliczeniowy { get => okresRozliczeniowy; set => okresRozliczeniowy = value; }
        [Display(Name = "Waluta")]
        public string Currency { get => currency; set => currency = value; }
        [Display(Name = "Praca zdalna")]
        public bool Remote { get => remote; set => remote = value; }
        [Display(Name = "Zdalna rozmowa rekrutacyjna")]
        public bool RemoteInterview { get => remoteInterview; set => remoteInterview = value; }
        public bool IsDeleted { get => isDeleted; set => isDeleted = value; }
        [Display(Name = "Data wygaśnięcia")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ExpirationDate { get => expirationDate; set => expirationDate = value; }
    }

    public class Application
    {
        [Key, Column(Order = 0)]
        [ForeignKey("ExtendedUser") ]
        public string ExtendedUser_Id { get; set; }
        [Key, Column(Order = 1)]
        [ForeignKey("JobOffer")]
        public int JobOffer_Id { get; set; }

        public virtual ExtendedUser ExtendedUser { get; set; }
        public virtual JobOffer JobOffer { get; set; }

        public bool GotInterview { get; set; }
        public bool GotJobOffer { get; set; }
    }
}

Recruitment_Support_System/Controllers/HomeController.cs
using Recruitment_Support_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recruitment_Support_System.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Opis projektu.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Informacje o autorze.";
            return View();
        }

        public ActionResult JobOffers()
        {
            using (var db = new ApplicationDbContext())
                return View(db.JobOffers.Include("Company").Where(j=>j.IsDeleted != true).ToList());
        }
    }
}

Recruitment_Support_System/Controllers/JobsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Recruitment_Support_System.App_Start;
using Recruitment_Support_System.Helpers;
using Recruitment_Support_System.Models;
using Recruitment_Support_System.Models.ViewModels;
using RssMachineLearning;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Recruitment_Support_System.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {

        private ApplicationUserManager _userManager;
        private SingleHiddenLayerNeuralNetwork nn;

        public Func<string> GetUserId;
        public JobsController()
        {
            GetUserId = () => User.Identity.GetUserId();
        }

        public JobsController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
            GetUserId = () => User.Identity.GetUserId();
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Jobs
        [Authorize(Roles = "Company")]
        public async Task<ActionResult> Index()
        {
            var model = new List<JobOffer>();
            using (var db = new ApplicationDbContext())
            {
                var uid = GetUserId();
                var user = await UserManager.FindByIdAsync(uid);
                model = db.JobOffers.Where(j => j.Company.Owner.Id == user.Id).ToList();
                return View(model);
            }
        }

        [AllowAnonymous]
        [HandleError(ExceptionType = typeof(ArgumentException), View = "NotFound")]
        public ActionResult JobOffer(int? id, string returnUrl)
        {
            if (id == null)
            {
                throw new HttpException(404, "Not found");
            }
            if (string.IsNullOrEmpty(returnUrl))
            {
                returnUrl = "Home+Index";
            }
            using (var db = new ApplicationDbContext())
            {
                var userId = GetUserId();
                var returnUrls = returnUrl.Split('+');
                ViewBag.ReturnControllerUrl = returnUrls[0];
                ViewBag.ReturnUrl = returnUrls[1];
                var offer = db.JobOffers.Include("Company").Include("Applications").FirstOrDefault(jo => jo.Id == id);
                if (offer == null)
                {
                    throw new HttpException(404, "Not found");
                }
                if (offer.IsDeleted)
                {
                    ViewBag.Message = "Dana oferta już wygasła lub została usunięta. Nie można jej podejrzeć.";
                }
                JobViewModel model = new JobViewModel(offer);
                if (offer.Applications.Any(a => a.ExtendedUser_Id == userId))
                {
                    model.Applied = true;
                }
                else model.Applied = false;
                return View(model);

            }
        }

        public async Task<ActionResult> Applications(int id)
        {
            Dictionary<Application, double> keys = new Dictionary<Application, double>();
            nn = SingleHiddenLayerNeuralNetwork.GetInststance();
            using (var db = new ApplicationDbContext())
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                var model = db.Users.Include("Applications").Where(u => u.Applications.Any(a => a.JobOffer.Company.Owner.Id == user.Id && a.JobOffer_Id == id)).Distinct().ToList();
                List<ApplicationsViewModel> viewModel = new List<ApplicationsViewModel>();
                int i = 0;
                double[][] outputs = new double[model.Count][];
                foreach (var u in model)
                {
                    var appl = u.Applications.FirstOrDefault(a => a.JobOffer_Id == id);
                    outputs[i++] = nn.GenerateOutputs(AttributeHelper.getSingleRow(appl));
                    keys.Add(appl, AttributeHelper.addOutputValues(outputs[i - 1]));
                }


                var keyss = keys.OrderByDescending(k => k.Value);
                int j = 0;
                foreach (var k in keyss)
                {
                    var mod = db.Users.FirstOrDefault(e => e.Id == k.Key.ExtendedUser_Id);
                    ApplicationsViewModel exModel = new ApplicationsViewModel(mod, k.Key ?? new Application(), id);
                    viewModel.Add(exModel);
                }

                return View(viewModel);
            }
        }
        [Authorize]
        public async Task<ActionResult> Apply(int id)
        {
            using (var db = new ApplicationDbContext())
            {
                var userId = User.Identity.GetUserId();
                var user = db.Users.FirstOrDefault(u => u.Id == userId);
                if (!db.CVs.Any(c => c.User.Id == userId))
                {
                    throw new HttpException(404, "Nie znaleziono CV - najpierw stwórz swoje CV");
                }
                var jO = db.JobOffers.Include("Company").Include("Applications").FirstOrDefault(j => j.Id == id);
                if (jO == null)
                {
                    throw new HttpException(403, "Bad request");
                }
                jO.Applications.Add(new Application() { ExtendedUser_Id = userId, JobOffer_Id = jO.Id });
                db.SaveChanges();
                return View(new ApplyViewModel() { CompanyName = jO.Company.Name, JobTitle = jO.Title });
            }
        }
        [Authorize(Roles = "Company")]
        public async Task<ActionResult> DeleteOffer(int id)
        {
            using (var db = new ApplicationDbContext())
            {
                var jO = db.JobOffers.FirstOrDefault(j => j.Id == id);
                jO.IsDeleted = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public JsonResult UpdateGotInterview(bool check, string uid, int joId)
        {
            var currUserId = User.Identity.GetUserId();
            try
            {
                using (var db = new ApplicationDbContext())
                {

                    var user = db.Users.Include("Applications").FirstOrDefault(u => u.Id == uid);
                    var company = db.Companies.FirstOrDefault(c => c.Owner.Id == currUserId);
                    var app = user.Applications.FirstOrDefault(a => a.JobOffer_Id == joId);
                    app.GotInterview = !app.GotInterview;
                    db.SaveChanges();
                }
            }
            catch (Exception)
            {
                return Json("Fail");
            }
            return Json("Success");
        }
        public JsonResult UpdateGotJob(bool check, string uid, int joId)
        {
            var currUserId = User.Identity.GetUserId();
            try
            {
                using (var db = new ApplicationDbContext())
                {

                    var user = db.Users.Include("Applications").FirstOrDefault(u => u.Id == uid);
                    var company = db.Companies.FirstOrDefault(c => c.Owner.Id == currUserId);
                    var app = user.Applications.FirstOrDefault(a => a.JobOffer_Id == joId);
                    app.GotJobOffer = !app.GotJobOffer;
                    db.SaveChanges();
                }
            }
            catch (Exception) { return Json("Fail"); }

            return Json("Success");
        }
    }

}

Recruitment_Support_System/Views/Home/About.cshtml
@{
    ViewBag.Title = "Opracowanie i implementacja systemu wspomagania rekrutacji";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    Celem pracy jest projekt i implementacja systemu wspomagania rekrutacji, umożliwiającego zarządzanie
    danymi związanymi z procesem rekrutacji, analizę danych oraz ocenę nadsyłanych CV z zastosowaniem
    algorytmów uczenia maszynowego oraz języka C#.
</p>

Recruitment_Support_System/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Mariusz Lewczuk<br />
    Kielce<br />
    <abbr title="Numer telefonu">Telefon:</abbr>
    +48 725-502-788
    
</address>

<address>
    <strong>Email: </strong><a href="mailto:lewczuk.mariu@gmail.com">lewczuk.mariu@gmail.com</a><br />
</address>

Recruitment_Support_System/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Strona główna";
}

<div class="jumbotron">
    <h1>System wspierania rekrutacji</h1>
    <p class="lead">w skrócie SWR, to system który pomaga rekruterom wybrać odpowiedniego kandydata na wybrane stanowisko.</p>
    <p><a href="Home/JobOffers" class=" btn btn-raised btn-primary btn-lg">Zacznij teraz &raquo;</a></p>
</div>

Recruitment_Support_System/Views/Home/JobOffers.cshtml
@model IEnumerable<Recruitment_Support_System.Models.JobOffer>

@{
    ViewBag.Title = "Oferty";
}

<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
<div class="text-center">
    <input id="myInput" type="text" placeholder="Szukaj.." class="form-control form-control-underlined text-primary border-primary col-12 text-center">
    <hr />
</div>

<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobContract)
        </th>
        <th>
            Zarobki
        </th>
    </tr>
    <tbody id="myTable"
           @foreach (var item in Model) {<tr onclick="location.href = '@Url.Action("JobOffer", "Jobs", new { id=item.Id, returnUrl=HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString() + "+" + this.ViewContext.RouteData.Values["action"].ToString() })'">
            <td>
                @Html.DisplayFor(modelItem => item.Title) <a style="color:slategrey"> w @Html.DisplayFor(modelItem => item.Company.Name) </a> @if (item.RemoteInterview)
                {<i title="Zdana rozmowa kwalifikacyjna" class="fas fa-headset float-right"></i>}
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobLevel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobContract)
                @if (item.Remote)
                {<i title="Możliwość pracy zdalnej" class="fas fa-laptop-house float-right"></i>}
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZarobkiMin) - @Html.DisplayFor(modelItem => item.ZarobkiMax) @Html.DisplayFor(modelItem => item.Currency)
            </td>
        </tr>
    }
    </tbody>
</table>