Recruitment_Support_System/Controllers/CvController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Recruitment_Support_System.Helpers;
using Recruitment_Support_System.Models;
using Recruitment_Support_System.Models.Builders;
using Recruitment_Support_System.Models.Builders.CvBuilders;
using Recruitment_Support_System.Models.Builders.Direcors;
using Recruitment_Support_System.Models.CurriculumVitae;
using Recruitment_Support_System.Models.Dictionaries;
using Recruitment_Support_System.Models.Enums;
using Recruitment_Support_System.Models.ViewModels;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Recruitment_Support_System.Controllers
{
    [Authorize]
    public class CvController : Controller
    {
        private ApplicationUserManager _uM;
        private ApplicationDbContext dbContext;

        public Func<string> GetUserId;

        public ApplicationDbContext db { get => dbContext ?? new ApplicationDbContext(); set => dbContext = value; }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _uM ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _uM = value;
            }
        }

        public CvController()
        {

            GetUserId = () => User.Identity.GetUserId();
        }
        public CvController(ApplicationUserManager userManager)
        {
            _uM = userManager;
            GetUserId = () => User.Identity.GetUserId();
        }

        // GET: Cv
        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Index()
        {
            CV cV = (CV)Session["cV"];
            if (cV == null)
            {
                var user = await UserManager.FindByIdAsync(GetUserId());
                var userId = GetUserId();
                //var user = db.Users.First(u => u.Id == userId);
                cV = db.CVs.Include("User").Include("Courses").Include("Jobs").Include("Intrests").Include("Educations").Include("Languages.LanguageDictionary").Include("Skills").FirstOrDefault(cv => cv.User.Id == user.Id);
                if (cV != null)
                {
                    cV.LanguagesDictionary = db.LanguageDictionary.ToList();
                }
                else
                {
                    cV = new CV();
                    cV.LanguagesDictionary.AddRange(db.LanguageDictionary.ToList());
                }
                cV.LanguagesDictionary.Add(new LanguageDictionary() { Name = "Inny", CountryCode = "CC" });

                Session["cV"] = cV;
            }
            else
            {
                cV = (CV)Session["cV"];
            }

            return View(cV);

        }

        [Authorize(Roles = "User")]
        public ActionResult Job(Job job)
        {
            CV cV = (CV)Session["cV"];
            Job tmpJob = null;
            try
            {
                tmpJob = cV.Jobs.Where(i => i.Id == job.Id).First();
            }
            catch { }
            if (tmpJob == null)
            {
                cV.Jobs.Add(new Job() { CV = cV, Id = cV.Jobs.Any() ? cV.Jobs.Last().Id + 1 : 1, Name = job.Name, Company = job.Company, Comment = job.Comment, End = job.End, Start = job.Start });
            }
            else
            {
                UpdateHelper.UpdateJob(tmpJob, job);
            }
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]
        public ActionResult DeleteJob(int id)
        {
            CV cV = (CV)Session["cV"];
            cV.Jobs.Remove(cV.Jobs.Where(j => j.Id == id).First());
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]
        public ActionResult Education(Education education)
        {
            CV cV = (CV)Session["cV"];
            Education tmpEdu = null;
            try
            {
                tmpEdu = cV.Educations.Where(i => i.Id == education.Id).First();
            }
            catch { }
            if (tmpEdu == null)
            {
                cV.Educations.Add(new Education() { CV = cV, Id = cV.Educations.Any() ? cV.Educations.Last().Id + 1 : 1, Name = education.Name, Title = education.Title, End = education.End, Start = education.Start });
            }
            else
            {
                UpdateHelper.UpdateEducation(tmpEdu, education);
            }
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]
        public ActionResult DeleteEducation(int id)
        {
            CV cV = (CV)Session["cV"];
            cV.Educations.Remove(cV.Educations.Where(j => j.Id == id).First());
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]
        public ActionResult Course(Course course)
        {
            CV cV = (CV)Session["cV"];
            Course tmpCour = null;
            try
            {
                tmpCour = cV.Courses.Where(i => i.Id == course.Id).First();
            }
            catch { }
            if (tmpCour == null)
            {
                cV.Courses.Add(new Course() { CV = cV, Id = cV.Educations.Any() ? cV.Educations.Last().Id + 1 : 1, Name = course.Name, Org = course.Org, Passed = course.Passed, ValidTo = course.ValidTo });
            }
            else
            {
                UpdateHelper.UpdateCourse(tmpCour, course);
            }
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]
        public ActionResult DeleteCourse(int id)
        {
            CV cV = (CV)Session["cV"];
            cV.Courses.Remove(cV.Courses.Where(j => j.Id == id).First());
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]
        public ActionResult Skill(Skill skill)
        {
            CV cV = (CV)Session["cV"];
            Skill tmpSkill = null;
            try
            {
                tmpSkill = cV.Skills.Where(i => i.Id == skill.Id).First();
            }
            catch { }
            if (tmpSkill == null)
            {
                cV.Skills.Add(new Skill() { CV = cV, Id = cV.Educations.Any() ? cV.Educations.Last().Id + 1 : 1, Name = skill.Name, Level = skill.Level });
            }
            else
            {
                UpdateHelper.UpdateSkill(tmpSkill, skill);
            }
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]
        public ActionResult DeleteSkill(int id)
        {
            CV cV = (CV)Session["cV"];
            cV.Skills.Remove(cV.Skills.Where(j => j.Id == id).First());
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }
        [HttpPost]
        public void AddNewLanguage(int id, string name)
        {
            CV cV = (CV)Session["cV"];
            cV.LanguagesDictionary.Add(new LanguageDictionary() { Id = id, Name = name, CountryCode = name.Substring(0, 3) });
            Session["cV"] = cV;
        }

        [Authorize(Roles = "User")]
        public ActionResult Language(LanguageViewModel langu)
        {

            CV cV = (CV)Session["cV"];

            LanguageDictionary newLanguage = null;
            try
            {
                newLanguage = cV.LanguagesDictionary.Where(i => i.Id == langu.Language.Id).First();
            }
            catch { }
            //if(newLanguage == null)
            //{
            //    newLanguage = new LanguageDictionary() { Id = langu.Language.Id, Name = langu.Language.Name, CountryCode = langu.Language.Name.Substring(0,3) };
            //    cV.LanguagesDictionary.Add(newLanguage);
            //}

            Language tmpLang = null;
            try
            {
                tmpLang = cV.Languages.Where(i => i.Id == langu.MyLanguageId).First();
            }
            catch { }
            if (tmpLang == null)
            {
                cV.Languages.Add(new Language() { CV = cV, LanguageDictionary = newLanguage, Id = cV.Languages.Any() ? cV.Languages.Last().Id + 1 : 1, Level = langu.Level });
            }
            else
            {
                tmpLang.Level = langu.Level;
            }
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]
        public ActionResult DeleteLanguage(int id)
        {
            CV cV = (CV)Session["cV"];
            cV.Languages.Remove(cV.Languages.Where(j => j.Id == id).First());
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        public ActionResult Intrest(Intrest inter)
        {

            CV cV = (CV)Session["cV"];
            Intrest tmpInt = null;
            try
            {
                tmpInt = cV.Intrests.Where(i => i.Id == inter.Id).First();
            }
            catch { }
            if (tmpInt == null)
            {
                cV.Intrests.Add(new Intrest() { CV = cV, Name = inter.Name, Id = cV.Intrests.Any() ? cV.Intrests.Last().Id + 1 : 1 });
            }
            else
            {
                tmpInt.Name = inter.Name;
            }
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]
        public ActionResult DeleteIntrest(int id)
        {
            CV cV = (CV)Session["cV"];
            cV.Intrests.Remove(cV.Intrests.Where(j => j.Id == id).First());
            Session["cV"] = cV;
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User")]

Recruitment_Support_System/Controllers/JobsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Recruitment_Support_System.App_Start;
using Recruitment_Support_System.Helpers;
using Recruitment_Support_System.Models;
using Recruitment_Support_System.Models.ViewModels;
using RssMachineLearning;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Recruitment_Support_System.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {

        private ApplicationUserManager _userManager;
        private SingleHiddenLayerNeuralNetwork nn;

        public Func<string> GetUserId;
        public JobsController()
        {
            GetUserId = () => User.Identity.GetUserId();
        }

        public JobsController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
            GetUserId = () => User.Identity.GetUserId();
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Jobs
        [Authorize(Roles = "Company")]
        public async Task<ActionResult> Index()
        {
            var model = new List<JobOffer>();
            using (var db = new ApplicationDbContext())
            {
                var uid = GetUserId();
                var user = await UserManager.FindByIdAsync(uid);
                model = db.JobOffers.Where(j => j.Company.Owner.Id == user.Id).ToList();
                return View(model);
            }
        }

        [AllowAnonymous]
        [HandleError(ExceptionType = typeof(ArgumentException), View = "NotFound")]
        public ActionResult JobOffer(int? id, string returnUrl)
        {
            if (id == null)
            {
                throw new HttpException(404, "Not found");
            }
            if (string.IsNullOrEmpty(returnUrl))
            {
                returnUrl = "Home+Index";
            }
            using (var db = new ApplicationDbContext())
            {
                var userId = GetUserId();
                var returnUrls = returnUrl.Split('+');
                ViewBag.ReturnControllerUrl = returnUrls[0];
                ViewBag.ReturnUrl = returnUrls[1];
                var offer = db.JobOffers.Include("Company").Include("Applications").FirstOrDefault(jo => jo.Id == id);
                if (offer == null)
                {
                    throw new HttpException(404, "Not found");
                }
                if (offer.IsDeleted)
                {
                    ViewBag.Message = "Dana oferta już wygasła lub została usunięta. Nie można jej podejrzeć.";
                }
                JobViewModel model = new JobViewModel(offer);
                if (offer.Applications.Any(a => a.ExtendedUser_Id == userId))
                {
                    model.Applied = true;
                }
                else model.Applied = false;
                return View(model);

            }
        }

        public async Task<ActionResult> Applications(int id)
        {
            Dictionary<Application, double> keys = new Dictionary<Application, double>();
            nn = SingleHiddenLayerNeuralNetwork.GetInststance();
            using (var db = new ApplicationDbContext())
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                var model = db.Users.Include("Applications").Where(u => u.Applications.Any(a => a.JobOffer.Company.Owner.Id == user.Id && a.JobOffer_Id == id)).Distinct().ToList();
                List<ApplicationsViewModel> viewModel = new List<ApplicationsViewModel>();
                int i = 0;
                double[][] outputs = new double[model.Count][];
                foreach (var u in model)
                {
                    var appl = u.Applications.FirstOrDefault(a => a.JobOffer_Id == id);
                    outputs[i++] = nn.GenerateOutputs(AttributeHelper.getSingleRow(appl));
                    keys.Add(appl, AttributeHelper.addOutputValues(outputs[i - 1]));
                }


                var keyss = keys.OrderByDescending(k => k.Value);
                int j = 0;
                foreach (var k in keyss)
                {
                    var mod = db.Users.FirstOrDefault(e => e.Id == k.Key.ExtendedUser_Id);
                    ApplicationsViewModel exModel = new ApplicationsViewModel(mod, k.Key ?? new Application(), id);
                    viewModel.Add(exModel);
                }

                return View(viewModel);
            }
        }
        [Authorize]
        public async Task<ActionResult> Apply(int id)
        {
            using (var db = new ApplicationDbContext())
            {
                var userId = User.Identity.GetUserId();
                var user = db.Users.FirstOrDefault(u => u.Id == userId);
                if (!db.CVs.Any(c => c.User.Id == userId))
                {
                    throw new HttpException(404, "Nie znaleziono CV - najpierw stwórz swoje CV");
                }
                var jO = db.JobOffers.Include("Company").Include("Applications").FirstOrDefault(j => j.Id == id);
                if (jO == null)
                {
                    throw new HttpException(403, "Bad request");
                }
                jO.Applications.Add(new Application() { ExtendedUser_Id = userId, JobOffer_Id = jO.Id });
                db.SaveChanges();
                return View(new ApplyViewModel() { CompanyName = jO.Company.Name, JobTitle = jO.Title });
            }
        }
        [Authorize(Roles = "Company")]
        public async Task<ActionResult> DeleteOffer(int id)
        {
            using (var db = new ApplicationDbContext())
            {
                var jO = db.JobOffers.FirstOrDefault(j => j.Id == id);
                jO.IsDeleted = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public JsonResult UpdateGotInterview(bool check, string uid, int joId)
        {
            var currUserId = User.Identity.GetUserId();
            try
            {
                using (var db = new ApplicationDbContext())
                {

                    var user = db.Users.Include("Applications").FirstOrDefault(u => u.Id == uid);
                    var company = db.Companies.FirstOrDefault(c => c.Owner.Id == currUserId);
                    var app = user.Applications.FirstOrDefault(a => a.JobOffer_Id == joId);
                    app.GotInterview = !app.GotInterview;
                    db.SaveChanges();
                }
            }
            catch (Exception)
            {
                return Json("Fail");
            }
            return Json("Success");
        }
        public JsonResult UpdateGotJob(bool check, string uid, int joId)
        {
            var currUserId = User.Identity.GetUserId();
            try
            {
                using (var db = new ApplicationDbContext())
                {

                    var user = db.Users.Include("Applications").FirstOrDefault(u => u.Id == uid);
                    var company = db.Companies.FirstOrDefault(c => c.Owner.Id == currUserId);
                    var app = user.Applications.FirstOrDefault(a => a.JobOffer_Id == joId);
                    app.GotJobOffer = !app.GotJobOffer;
                    db.SaveChanges();
                }
            }
            catch (Exception) { return Json("Fail"); }

            return Json("Success");
        }
    }

}

Recruitment_Support_System/Views/Cv/CvPartials/_AddCourse.cshtml
@model Recruitment_Support_System.Models.CurriculumVitae.Course

<div class="modal-header">
    <h4>Kurs</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
@using (Html.BeginForm("Course", "CV", Model))
{
    @Html.AntiForgeryToken()

    <div class="modal-body">
        <div class="form-vertical card">
            <div class=" card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Org, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Org, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Org, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Passed, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Passed, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                        @Html.ValidationMessageFor(model => model.Passed, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ValidTo, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ValidTo, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                        @Html.ValidationMessageFor(model => model.ValidTo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
        <input type="submit" value="Zapisz" class="btn btn-primary" />
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Recruitment_Support_System/Views/Cv/CvPartials/_AddEducation.cshtml
@model Recruitment_Support_System.Models.CurriculumVitae.Education

<div class="modal-header">
    <h4>Edukacja</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
@using (Html.BeginForm("Education", "CV",Model))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()

        <div class="form-vertical card">
            <div class=" card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
        <input type="submit" value="Zapisz" class="btn btn-primary" />
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Recruitment_Support_System/Views/Cv/CvPartials/_AddIntrest.cshtml
@model Recruitment_Support_System.Models.CurriculumVitae.Intrest


<div class="modal-header">
    <h4>Zainteresowania</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
@using (Html.BeginForm("Intrest", "CV", Model))
{

<div class="modal-body">
    @Html.AntiForgeryToken()

    <div class="form-vertical card">
        <div class=" card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
</div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
        <input type="submit" value="Zapisz" class="btn btn-primary" />
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Recruitment_Support_System/Views/Cv/CvPartials/_AddJob.cshtml
@model Recruitment_Support_System.Models.CurriculumVitae.Job

<div class="modal-header">
    <h4>Job</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
@using (Html.BeginForm("Job","CV",Model))
{
    @Html.AntiForgeryToken()

    <div class="modal-body">
        <div class="form-vertical card">
            <div class=" card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
        <input type="submit" value="Zapisz" class="btn btn-primary" />
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Recruitment_Support_System/Views/Cv/CvPartials/_Education.cshtml
@model IEnumerable<Recruitment_Support_System.Models.CurriculumVitae.Education>

<h5>Edukacja</h5>

<table class="table table-bordered table-striped table-hover">
    @*<colgroup>
            <col span="1" style="width: 8%;">
            <col span="1" style="width: 8%;">
            <col span="1" style="width: 8%;">
            <col span="1" style="width: 8%;">
            <col span="1" style="width: 11.5%;">
        </colgroup>*@
    <tr class="thead-light">
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th width="100px">
            @*@Html.DisplayNameFor(model => model.Start)
                @Html.DisplayNameFor(model => model.End)*@
            Od - Do
        </th>
        @*<th>
            </th>*@
        <th style="width : 65px"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr data-toggle="modal" data-target="@("#editedumodal" + item.Id)">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Start)
                @if (item.End.Equals(DateTime.MinValue))
                {
                    <label>Obecnie</label>
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.End)
                }
            </td>
            @*<td>
                </td>*@
            <td>
                @*<label type="button" class="btn btn-dark" data-toggle="modal" data-target=@("#editedumodal" + item.Id)><i class="fa fa-edit"></i></label>*@
                @*@Html.ActionLink("Details", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-outline-info btn-md m-0 px-3" })*@
                <a href="@Url.Action("DeleteEducation", "Cv", new { id = item.Id })" class="btn btn-dark"><i class="fa fa-trash"></i></a>
            </td>
        </tr>
        <div id=@("editedumodal" + item.Id ) class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">

                    @{
                        Html.RenderPartial("CvPartials/_AddEducation", item);
                    }
                </div>
            </div>
        </div>
    }

</table>